### ISSUE TITLE
[Feature Request]: Would like a means to bulk "store" cows as an inventory item

### ISSUE THREAD

**Issue by mahldcat** [DoctorFTB/FluidCows#10]
Use Case:

I have a bunch of cows that I currently leave penned up in my farm.  Their use is purely as breeding stock, and am not collecting the fluids they produce.  This leads to additional load on the server if the farm is chunk loaded, and the risk of losing my breeding stock in the event of an admin having to purge all entities off the server due to performance issues.  

Proposal:  What if the halter were extended with an additional behavior
     Normal Pick up/Placement remains unchanged
     Shift-Right-Click on a fluid cow will turn it into one of the cow inventory items that can be picked up (make these stackable)?

Game balance issues:
Add a durability to the halter (make the max durability configurable along with the amount of wear caused by each action)?
Maintain a partial state for the converted cows:  (in this case track if the cow was a baby or an adult), and when the player decides to convert the cow item back into a cow entity, it would use that state (baby/adult) with all timers reset to zero.

As another idea:  Make the baby/adult option a configurable/craft tweakable option? (useful if a modpack wanted to make fluid cows craftable).

**Comment by DoctorFTB** [comment]
About ur farm with breeding stock: u have same lags if u have farm with vanilla cows / pigs / sheeps / etc.
(Where u see lags?)
~
About convert cow to displayer: No, because cooldown reset.
~
About durability: No, because items from other mods (like EX2) have items to move entities without durability.
~
About fluid cows craft: Mod have support craft cows.
Examples from StoneBlock 2:

recipes.addShaped(<fluidcows:cow_displayer>.withTag({fluid: "lava"}), [
  [<minecraft:leather>, <minecraft:leather>, <minecraft:leather>],
  [<minecraft:leather>, <minecraft:lava_bucket>, <minecraft:leather>],
  [<minecraft:leather>, <minecraft:leather>, <minecraft:leather>]
]);

recipes.addShaped(<fluidcows:cow_displayer>.withTag({fluid: "water"}), [
  [<minecraft:leather>, <minecraft:leather>, <minecraft:leather>],
  [<minecraft:leather>, <minecraft:water_bucket>, <minecraft:leather>],
  [<minecraft:leather>, <minecraft:leather>, <minecraft:leather>]
]);

recipes.addShaped(<fluidcows:cow_displayer>.withTag({fluid: "milk"}), [
  [<minecraft:leather>, <minecraft:leather>, <minecraft:leather>],
  [<minecraft:leather>, <minecraft:milk_bucket>, <minecraft:leather>],
  [<minecraft:leather>, <minecraft:leather>, <minecraft:leather>]
]);

recipes.addShaped(<fluidcows:cow_displayer>.withTag({fluid: "stone"}), [
  [<minecraft:leather>, <minecraft:leather>, <minecraft:leather>],
  [<minecraft:leather>, <forge:bucketfilled>.withTag({FluidName: "stone", Amount: 1000}), <minecraft:leather>],
  [<minecraft:leather>, <minecraft:leather>, <minecraft:leather>]
]);

**Comment by DoctorFTB** [comment]
@mahldcat
