### ISSUE TITLE
[Question] Fluid Cow Breeding Chances

### ISSUE THREAD

**Issue by MonfGeiger** [DoctorFTB/FluidCows#18]
I'm playing stoneblock 2 since I finished and loved stoneblock 1, and im finally starting fluid cows, but I saw therre's a growth accelerator for fluid cows. I have a 15x15x15 room styled ouyt for fluid cow breeding, and I'd like to know what the A.O.E is for the growth accelerator if I place it in the exact middle of the room

Is therre a max block range, does it function only in the boundaries of whatever chunk its in?
these are answers I'd like to know, please and thank you

**Comment by DoctorFTB** [comment]
By default in Fluid Cows - radius work for Accelerator is 5.
(you can get in config "AcceleratorRadius" "Accelerator working radius")
Like if u have 5 in config:
Radius 1 + 5 * 2 = 11.
= 11x11x11 radius, block in center
For 15x15 u need 4 accelerators (because u have 11 from one accelerator but u need 15).

**Comment by MonfGeiger** [comment]
last question before closing it: im trying to breed energetic silver with resonant ender to get vivid alloy, but im not getting vivid alloy; how rare is it to get a vivid alloy cow?

**Comment by DoctorFTB** [comment]
You can check your chance by using JEI.
(Click to displayer, and u see chance)

**Comment by DoctorFTB** [comment]
Any other questions? Or close issue
